"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Gem, RefreshCw, ShieldCheck, Truck } from "lucide-react";

const fallbackCategories = [
 ["Rings","rings","https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=85"],
 ["Earrings","earrings","https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=85"],
 ["Necklaces","necklaces","https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=900&q=85"],
 ["Bangles","bangles","https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=900&q=85"],
 ["Bridal","bridal","https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=900&q=85"],
 ["Men's Edit","mens-jewellery","https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=900&q=85"]
];
const pieces = [
 ["Celestial Polki Necklace","₹18,900","necklaces","https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=900&q=90"],
 ["Noor Emerald Drops","₹7,450","earrings","https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=90"],
 ["Aarvi Diamond Band","₹12,600","rings","https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=90"],
 ["Meher Gold Bangle","₹9,800","bangles","https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=900&q=90"]
];
export default function Home(){
 const [adminCategories,setAdminCategories]=useState([]);
 useEffect(()=>{fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api"}/categories`).then(r=>r.json()).then(data=>setAdminCategories(Array.isArray(data)?data:[])).catch(()=>setAdminCategories([]))},[]);
 const categories=adminCategories.length?adminCategories.slice(0,6).map((cat,index)=>[cat.name,cat.slug,cat.image_url||fallbackCategories[index%fallbackCategories.length][2]]):fallbackCategories;
 return <div className="bg-[#f8f4ed] text-[#201713]">
 <section className="relative min-h-[calc(100vh-104px)] overflow-hidden bg-[#1c1210] text-white"><img src="https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1800&q=90" alt="Fine jewellery" className="absolute inset-0 h-full w-full object-cover opacity-60"/><div className="absolute inset-0 bg-gradient-to-r from-[#160d0b] via-[#160d0b]/75 to-transparent"/><div className="relative mx-auto flex min-h-[calc(100vh-104px)] max-w-[1440px] items-center px-6 py-24 md:px-14"><div className="max-w-2xl"><p className="section-kicker">The Heirloom Collection · 2026</p><h1 className="font-serif text-5xl font-light leading-[.96] md:text-8xl">Jewels that hold<br/><em className="text-[#d8b77d]">your story.</em></h1><p className="mt-7 max-w-lg text-sm leading-7 text-white/70">Modern heirlooms shaped by Indian artistry. Thoughtfully crafted for celebrations, promises and everything in between.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/category/new-arrivals" className="flex items-center gap-3 bg-[#d8b77d] px-7 py-4 text-[10px] font-bold uppercase tracking-[.24em] text-[#1c1210]">Explore collection <ArrowRight size={14}/></Link><Link href="/category/bridal" className="border border-white/30 px-7 py-4 text-[10px] font-bold uppercase tracking-[.24em]">Discover bridal</Link></div></div></div></section>
 <div className="border-b border-[#ded3c4] bg-[#efe6d8] py-4"><div className="mx-auto flex max-w-[1440px] flex-wrap justify-center gap-x-14 gap-y-2 px-6 text-[9px] font-semibold uppercase tracking-[.25em] text-[#6e5747]"><span>Hallmarked purity</span><span>Certificate of authenticity</span><span>Complimentary insured shipping</span><span>Lifetime care</span></div></div>
 <section className="mx-auto max-w-[1440px] px-6 py-20 md:px-14 md:py-28"><div className="mb-12"><p className="section-kicker">Find your treasure</p><h2 className="section-title">Shop by <em>category</em></h2></div><div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">{categories.map(([name,slug,image])=><Link key={slug} href={`/category/${slug}`} className="group text-center"><div className="aspect-[4/5] overflow-hidden bg-[#e8ded0]"><img src={image} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><p className="mt-4 font-serif text-lg">{name}</p><span className="text-[8px] uppercase tracking-[.24em] text-[#9a8069]">Explore</span></Link>)}</div></section>
 <section className="grid bg-[#261815] text-white lg:grid-cols-2"><img src="https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=1400&q=90" alt="Craftsmanship" className="min-h-[520px] h-full w-full object-cover"/><div className="flex items-center px-8 py-20 md:px-20"><div><p className="section-kicker">Made by hand</p><h2 className="font-serif text-4xl font-light md:text-6xl">An ode to enduring <em className="text-[#d8b77d]">craft.</em></h2><p className="mt-7 max-w-lg text-sm leading-7 text-white/65">Every KIA Jewellers piece passes through the hands of master artisans—stone setters, polishers and storytellers preserving generations of knowledge.</p><Link href="/category/signature" className="mt-9 inline-flex items-center gap-3 border-b border-[#d8b77d] pb-2 text-[10px] font-bold uppercase tracking-[.24em]">Signature pieces <ArrowRight size={13}/></Link></div></div></section>
 <section className="mx-auto max-w-[1440px] px-6 py-20 md:px-14 md:py-28"><div className="mb-12 text-center"><p className="section-kicker">Curated for you</p><h2 className="section-title">Objects of <em>desire</em></h2></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{pieces.map(([name,price,slug,image])=><Link key={name} href={`/category/${slug}`} className="group"><div className="aspect-[4/5] overflow-hidden bg-[#e8ded0]"><img src={image} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><h3 className="mt-4 font-serif text-lg md:text-xl">{name}</h3><p className="mt-1 text-xs text-[#826b5b]">{price}</p></Link>)}</div></section>
 <section className="relative mx-4 overflow-hidden md:mx-8"><img src="https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=1800&q=90" alt="Bridal jewellery" className="h-[580px] w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/75 to-transparent"/><div className="absolute inset-0 flex items-center px-8 md:px-20"><div className="text-white"><p className="section-kicker">The bridal atelier</p><h2 className="font-serif text-5xl font-light md:text-7xl">For your forever<br/><em className="text-[#e1c28d]">beginning.</em></h2><Link href="/category/bridal" className="mt-8 inline-flex bg-white px-7 py-4 text-[10px] font-bold uppercase tracking-[.24em] text-[#1c1210]">Explore bridal</Link></div></div></section>
 <section className="mx-auto grid max-w-[1200px] grid-cols-2 gap-8 px-6 py-20 md:grid-cols-4">{[[Gem,"Certified quality","Purity you can trust"],[Truck,"Insured delivery","Complimentary pan-India"],[RefreshCw,"Easy exchange","Simple 15-day exchange"],[ShieldCheck,"Lifetime care","Cleaning & repair support"]].map(([Icon,title,text])=><div key={title} className="text-center"><Icon className="mx-auto mb-4 text-[#a67c3d]" size={22}/><h3 className="text-[10px] font-bold uppercase tracking-[.22em]">{title}</h3><p className="mt-2 text-xs text-[#8a7566]">{text}</p></div>)}</section>
 </div>}
